### ISSUE TITLE
Is the scale fixed in the shader code?

### ISSUE THREAD

**Issue by BeebBenjamin** [jcanofuentes/scan_and_shade#1]
![image](https://github.com/jcanofuentes/scan_and_shade/assets/4963887/9d0895ad-0db6-4106-a7ec-2611c1b2cd0a)

I have attempted to add the custom shader from pipeline 1 in place of the default material in the Mirador plug-in.  I am getting something happening.  You can see the image is very dim.  Is that pin prick the light?

**Comment by jcanofuentes** [comment]
It is difficult to say what it is, but it could be. If it's OK with you, I can try to integrate it myself. The problem is that I haven't managed to set up a working setup with the latest version of the code. do you think you could help me? On the other hand, I'm going to send you my personal email to have a more direct channel.

**Comment by BeebBenjamin** [comment]
I know what it is.  It is light distance.  Due to the scale of my meshes or my orthographic camera a distance of 1 makes the light tiny.  Here it is with the distance set to 1000.

![image](https://github.com/jcanofuentes/scan_and_shade/assets/4963887/b3905a78-dd7e-4901-ab18-221dc989bfbd)

Sure, I can help.

**Comment by jcanofuentes** [comment]
Looks promising!
